project_id = "fcfdyivyjidzqjtanalq"

[functions.get-posts]
verify_jwt = true

[functions.update-post]
verify_jwt = true

[functions.delete-post]
verify_jwt = true

[functions.delete-media]
verify_jwt = true

[functions.store-platform-integration]
verify_jwt = true

[functions.get-platform-integration]
verify_jwt = true

[functions.update-platform-integration]
verify_jwt = true

[functions.update-story]
verify_jwt = true

[functions.delete-story]
verify_jwt = true

[functions.get-login-activity]
verify_jwt = true

[functions.revoke-other-session]
verify_jwt = true

[functions.validate-openai-key]
verify_jwt = true
