project_id = "fcfdyivyjidzqjtanalq"

[functions.get-posts]
verify_jwt = false

[functions.update-post]
verify_jwt = false

[functions.delete-post]
verify_jwt = false

[functions.delete-media]
verify_jwt = false

[functions.store-platform-integration]
verify_jwt = false

[functions.get-platform-integration]
verify_jwt = false

[functions.update-platform-integration]
verify_jwt = false